### ISSUE TITLE
通配符证书剩余0天

### ISSUE THREAD

**Issue by xjzyy** [mouday/domain-admin#105]
通配符证书剩余0天；希望修复一下

**Comment by mouday** [comment]
通配符没法查询到期时间，需要具体的子域名

**Comment by xjzyy** [comment]
![image](https://github.com/mouday/domain-admin/assets/29560190/fb5d4fcd-e863-466f-beb7-bf7e6646aba5)
![image](https://github.com/mouday/domain-admin/assets/29560190/7aa7d4f6-d3ee-43b8-ae2b-a596f7f4c8b9)
 都是在阿云买的一个显示一个不显示。

**Comment by mouday** [comment]
像是那个应该是bug，获取证书的原理是访问网站获取证书，解析时间，和浏览器一样，通配符是没法访问的

**Comment by xjzyy** [comment]
我懂你的意思了 ；访问A.com -->跳转到 https://:www.A.com 才能监控到SSL证书；

我下面网站没有做B.com 跳转到https://:www.B.com 所以监控不到证书。
