### ISSUE TITLE
定时任务无法正常执行

### ISSUE THREAD

**Issue by xhd0625** [mouday/domain-admin#11]
这个项目我很需要，但似乎遇到了一些问题，程序以docker方式运行，在“监测日志”里历史执行状态全都是失败，“错误日志”一栏为“-”，我想请问日志在哪里查看？
另外，配置了163的发件邮箱后，向腾讯邮箱发邮件都会被腾讯退回。

**Comment by mouday** [comment]
具体的日志可以在logs目录下查看
邮件被退回，这应该是腾讯邮箱的安全策略，换个邮箱试试
目前我使用的就是163邮箱发送到qq邮箱，一切正常

还可以加入交流群问问群友

**Comment by xhd0625** [comment]
`Adding job tentatively -- it will be properly scheduled when the scheduler starts
Added job "update_and_check_all_domain_cert" to job store "default"
Scheduler started
Looking for jobs to run
Next wakeup is due at 2023-04-02 10:30:00+08:00 (in 84118.746757 seconds)

Adding job tentatively -- it will be properly scheduled when the scheduler starts
Added job "update_and_check_all_domain_cert" to job store "default"
Scheduler started
Looking for jobs to run
Next wakeup is due at 2023-04-02 10:30:00+08:00 (in 83791.465329 seconds)

Adding job tentatively -- it will be properly scheduled when the scheduler starts
Added job "update_and_check_all_domain_cert" to job store "default"
Scheduler started
Looking for jobs to run
Next wakeup is due at 2023-04-02 10:30:00+08:00 (in 83709.602014 seconds)

Adding job tentatively -- it will be properly scheduled when the scheduler starts
Added job "update_and_check_all_domain_cert" to job store "default"
Scheduler started
Looking for jobs to run
Next wakeup is due at 2023-04-02 10:30:00+08:00 (in 83546.940595 seconds)

Adding job tentatively -- it will be properly scheduled when the scheduler starts
Added job "update_and_check_all_domain_cert" to job store "default"
Scheduler started
Looking for jobs to run
Next wakeup is due at 2023-04-02 10:30:00+08:00 (in 83424.659750 seconds)

Adding job tentatively -- it will be properly scheduled when the scheduler starts
Added job "update_and_check_all_domain_cert" to job store "default"
Scheduler started
Looking for jobs to run
Next wakeup is due at 2023-04-02 10:30:00+08:00 (in 81482.176865 seconds)

Looking for jobs to run
Running job "update_and_check_all_domain_cert (trigger: cron[month='*', day='*', day_of_week='*', hour='10', minute='30'], next run at: 2023-04-02 10:30:00 CST)" (scheduled at 2023-04-02 10:30:00+08:00)
Next wakeup is due at 2023-04-03 10:30:00+08:00 (in 86399.979406 seconds)
Job "update_and_check_all_domain_cert (trigger: cron[month='*', day='*', day_of_week='*', hour='10', minute='30'], next run at: 2023-04-03 10:30:00 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/domain_admin/service/domain_service.py", line 211, in update_and_check_all_domain_cert
    update_all_domain_cert_info()
  File "/app/domain_admin/service/domain_service.py", line 120, in update_all_domain_cert_info
    update_domain_cert_info(row)
  File "/app/domain_admin/service/domain_service.py", line 71, in update_domain_cert_info
    domain_start_time = domain_info.get('start_time')
AttributeError: 'NoneType' object has no attribute 'get'`

感谢回复！这是我在“apscheduler.log”文件中截取到的片段，我观察到有多条“2023-04-02 10:30:00+08:00”的“Adding job”信息，但更加重要的是，我观察到抛出了空类型对象的属性调用异常。每天都是抛出这个异常。

**Comment by mouday** [comment]
你的域名可以正常访问吗

**Comment by mouday** [comment]
试试升级到最新版本，这个问题可能修复了

**Comment by xhd0625** [comment]
我们有一个一级域名证书，建立了若干二级站点，启用SSL的大概有200多个二级站点，我无法保证所有的站点在任务运行时都是可用的。目前我的版本是1.1.8，之前的几个版本都是有这个问题的，我稍后尝试一下1.2.1版本

**Comment by mouday** [comment]
解决了吗？

**Comment by xhd0625** [comment]
是的，新版本解决了我的问题

**Comment by mouday** [comment]
QQ群号:731742868，有问题可以更快的得到响应
