### ISSUE TITLE
【功能请求】增加域名备案查询接口支持

### ISSUE THREAD

**Issue by richard-lb** [mouday/domain-admin#112]
现有的3个接口都已经无法使用了，备案信息无法显示，可否考虑新增如下查询接口支持
接口地址：https://api.uomg.com/api/icp
接口文档：https://api.uomg.com/doc-icp.html#api

**Comment by mouday** [comment]
好的，多谢反馈

**Comment by mouday** [comment]
测试了几次，发现接口不稳定
```json
{
    "code": 1,
    "domain": "qq.com",
    "icp": "未备案"
}
```

**Comment by richard-lb** [comment]
确实，我再去测试的时候也有问题了，目前免费的api都不好用了，感谢及时响应
