### ISSUE TITLE
证书下载文件名修改建议

### ISSUE THREAD

**Issue by fcwys** [mouday/domain-admin#113]
现在下载的通配符证书压缩包内文件名为 `*.xx.com.pem`，在Windows下会提示文件名错误，建议涉及泛域名的修改为_.xx.com这种格式

**Comment by mouday** [comment]
好的

**Comment by mouday** [comment]
- v1.6.39(2024-07-05)
    - 修改证书导出命名格式 fix#113
    - 修复通配符域名多级子域名判定错误
