### ISSUE TITLE
建议申请SSL证书时增加验证RUL修改编辑

### ISSUE THREAD

**Issue by appleftg** [mouday/domain-admin#119]
你好，验证文件上传了，不一定是80端口，希望申请SSL证书时，增加验证URL编辑修改功能，以便验证，谢谢

**Comment by mouday** [comment]
这个是letencrypt规定的，只能用80端口，不过你可以配置301跳转

**Comment by appleftg** [comment]
> 这个是letencrypt规定的，只能用80端口，不过你可以配置301跳转
好的，谢谢，晚点试试

**Comment by appleftg** [comment]
> 这个是letencrypt规定的，只能用80端口，不过你可以配置301跳转

好的，谢谢，晚点试试
