### ISSUE TITLE
API证书部署做了个小工具

### ISSUE THREAD

**Issue by Gourds** [mouday/domain-admin#121]
感谢作者的开源系统，很好用。

- 提个小建议，意见部署的内置命令可以加上sudo

我写的这个工具主要是方便灵活部署的，通过配置文件对更新命令进行映射一定程度避免危险命令，有需要的可以尝试下。

https://github.com/Gourds/domain-admin-ssl-deploy

**Comment by mouday** [comment]
很强！

**Comment by mouday** [comment]
部署命令，可以自定义的

https://domain-admin.readthedocs.io/zh-cn/latest/manual/install.html#id6
