### ISSUE TITLE
.shop 的域名好像获取不到域名到期天数

### ISSUE THREAD

**Issue by trojan20161207** [mouday/domain-admin#130]
版本是v.1.6.21 
域名是在godaddy买的 大佬有时间帮忙给处理一下
<img width="1286" alt="image" src="https://github.com/user-attachments/assets/7d43c3bd-1c17-4b72-9995-669f2962aedf">
看了一下 也没有报错日志

**Comment by mouday** [comment]
收到

**Comment by trojan20161207** [comment]
换了个服务器好了，可能是dns问题
