### ISSUE TITLE
是否考虑下把网站状态一同监控报警了

### ISSUE THREAD

**Issue by zsinba** [mouday/domain-admin#17]
当前监控证书,域名的状态,是基于网站 的URL访问及其他数据; 

考虑一下, 把网站(或者指定的URL)的http(s)返回码一并监控+报警了.
同类的平台虽然很多, 但是当前多这一个或者可以方便很多. 指定URL或者指定的域名访问http(S)返回http状态码,如果不在指定的值,则报警. 用于监控网站运行状态.

作者可以考虑一下这个功能,是否值得添加. 
本来就有这块功能,只是没有特意放出来 . 不如考虑一下.

**Comment by mouday** [comment]
好的，感谢提供建议

**Comment by zsinba** [comment]
很好的工具. 小而美,非常有用.

再深入一下点的话, 可以再加上快到期后, 自动从acme.sh申请证书, 然后提供证书下载.
通过配置dnspod,aliyun ,godaddy 等的ak,sk等就可以用脚本申请下来.
用不用是用户自己的事情, 有这些小而美的功能,或者会有不同的收获.

再次感谢作者提供的工具,很好用的. 
之前 一直使用的是:https://myssl.com/ 这个也不错, 微信订阅一下可以关闭自己的网站.
而且可以检查证书的安全等级.

**Comment by mouday** [comment]
好的，我们会逐步完善功能

**Comment by mouday** [comment]
v1.6.2版本已新增网站状态监控
