### ISSUE TITLE
如何自定义设置距离到期前多长时间发送提醒？

### ISSUE THREAD

**Issue by fortheddy** [mouday/domain-admin#19]
能否自定义设置域名注册到期或者证书到期前多长时间开始发送通知，以及通知的次数或频率？？

**Comment by mouday** [comment]
点击头像下拉，就可以设置

**Comment by splintereddy** [comment]
那通知的频率呢？比如通过webhook的方式，是只会发送一次通知还是可以重复多次？

**Comment by mouday** [comment]
只要小于你设置的天数，每天都会发送
