### ISSUE TITLE
请问这个index.html文件怎么来的呢

### ISSUE THREAD

**Issue by qq516249940** [mouday/domain-admin#20]
msg": "[Errno 2] No such file or directory: '/app/domain_admin/public/index.html'"，根据你的dockerfile 编译出来的镜像，跑是有问题的

**Comment by mouday** [comment]
给你开了权限，https://github.com/mouday/domain-admin-web

拉取dist分支到public目录下即可
<img width="1012" alt="image" src="https://github.com/mouday/domain-admin/assets/24365682/6b36aa6a-bbb3-4eb9-a878-b6f299d88247">

**Comment by ayunwSky** [comment]
@mouday  给我开个权限，或者你直接 public就行了呗

**Comment by mouday** [comment]
> @mouday 给我开个权限，或者你直接 public就行了呗

已开权限

**Comment by seascheng** [comment]
您好，这个项目被收录进了[HelloGitHub 86期](https://hellogithub.com/periodical/volume/86)，所以估计这几天应该会很多试用者，所以能否直接public web端？

**Comment by mouday** [comment]
> 您好，这个项目被收录进了[HelloGitHub 86期](https://hellogithub.com/periodical/volume/86)，所以估计这几天应该会很多试用者，所以能否直接public web端？

好的，感谢推广，可以开放个大家
