### ISSUE TITLE
建议新增 freenom 的支持

### ISSUE THREAD

**Issue by mayjack0312** [mouday/domain-admin#26]
[修好后](https://github.com/mouday/domain-admin/issues/24#issuecomment-1567831570)试了一下，不知道是因为网不通还是程序本身不支持freenom域名的原因
导入后全部显示红叉子，到期时间什么的全部不显示

**Comment by mouday** [comment]
ml tk等后缀域名查询不到注册信息

**Comment by mayjack0312** [comment]
> ml tk等后缀域名查询不到注册信息

噢噢，原来是这样，明白了，谢谢 ღ( ´･ᴗ･` )
