### ISSUE TITLE
域名字体很奇怪，i变成大写？

### ISSUE THREAD

**Issue by shiqianwei0508** [mouday/domain-admin#28]
![image](https://github.com/mouday/domain-admin/assets/5445791/6897b9de-1c27-4b1c-b534-152548985d28)

**Comment by mouday** [comment]
怎么出现的？所有的i都会变大写吗？

**Comment by shiqianwei0508** [comment]
> 怎么出现的？所有的i都会变大写吗？

添加完域名就出现了，域名管理页面的所有域名的i都是I，但是，其他页面（比如分组管理关联域名页面）是正常的。

部署方式是docker

**Comment by baymax55** [comment]
我用最新的代码跑起来后没有复现
![image](https://github.com/mouday/domain-admin/assets/35788491/f8f7c2cb-dc07-411a-8e8b-bc9ca2e7838a)

**Comment by mouday** [comment]
可能是系统字体库的原因

**Comment by shiqianwei0508** [comment]
跟系统字体有关系，我换了一台电脑，字体就正常显示了。
