### ISSUE TITLE
更新域名证书报错

### ISSUE THREAD

**Issue by zreaty** [mouday/domain-admin#32]
<img width="379" alt="image" src="https://github.com/mouday/domain-admin/assets/27671886/5d8508b5-150a-45c0-87d4-f33663ba09c4">
地址本身能打开

**Comment by mouday** [comment]
可以发一下地址吗

**Comment by zreaty** [comment]
加了下域名ip地址 复现不了了
![Uploading image.png…]()
![Uploading image.png…]()
不过这个问题可以查一下

**Comment by zreaty** [comment]
添加了一下域名主机 复现不了了 不过添加域名主机有点问题

**Comment by zreaty** [comment]
添加了一下域名主机 复现不了了 不过添加域名主机有点问题，第一次提交报错，第二次提交显示已存在
<img width="402" alt="image" src="https://github.com/mouday/domain-admin/assets/27671886/10ac7d2f-4cee-4e90-b769-5f904b5a8bfc">

**Comment by mouday** [comment]
已修复 v1.4.2
