### ISSUE TITLE
希望大佬可以添加【无需账号密码SSL验证】即可发送邮件这一功能

### ISSUE THREAD

**Issue by spysir** [mouday/domain-admin#33]
我的SMTP服务器是自建的，没有发件人账号,密码,SSL,这些验证设置，仅主机+端口就可以发送邮件，希望大佬可以添加【无需账号密码SSL验证】即可发送邮件这一功能
![Snipaste_2023-06-22_09-36-06](https://github.com/mouday/domain-admin/assets/59646715/96cd51b0-c53e-41e3-99ee-b8c605c269bd)

**Comment by mouday** [comment]
最新版本已支持，有空测试一下
