### ISSUE TITLE
最新邮件通知域名数量有限制？

### ISSUE THREAD

**Issue by shiqianwei0508** [mouday/domain-admin#34]
![image](https://github.com/mouday/domain-admin/assets/5445791/3c50864b-469f-4f3f-b91d-e2d8e6f7ba16)
![image](https://github.com/mouday/domain-admin/assets/5445791/a8795b2a-e3da-4c88-8b69-b9486ba805b5)

**Comment by mouday** [comment]
新版本，我仅发送临近过期的域名或证书信息，避免数据过大

**Comment by shiqianwei0508** [comment]
> 新版本，我仅发送临近过期的域名或证书信息，避免数据过大

那应该是推送60天内，或者30天内的吧？不能只推送前25条吧。我这前二十五条全是过期不用的域名，剩余天数都是0。所以我收到的邮件通知全是无效信息。或者给我个设置？让我可以设置通知的域名？

**Comment by mouday** [comment]
可以设置天数，默认是3天，也可以在域名列表设置不监控

<img width="643" alt="image" src="https://github.com/mouday/domain-admin/assets/24365682/2cc9bba3-c7b9-411d-b918-958b2838a5aa">

<img width="786" alt="image" src="https://github.com/mouday/domain-admin/assets/24365682/ca873217-be43-43bb-99a0-a9c38bda9cf7">
