### ISSUE TITLE
无法收到每日通知了

### ISSUE THREAD

**Issue by shiqianwei0508** [mouday/domain-admin#35]
经过排查，通知邮件都发送到  admin@mycomany.com 了。

![image](https://github.com/mouday/domain-admin/assets/5445791/3bbf2ab8-48fe-4c30-9231-0c09eda7f544)

这个邮件地址在哪里配置呢？

并且，为什么每小时发送一次？
![image](https://github.com/mouday/domain-admin/assets/5445791/d5df423a-4605-4ab6-9411-84d924aa67b1)

通知设置里面，我设置了邮件接收地址的。
![image](https://github.com/mouday/domain-admin/assets/5445791/33330d8b-21fe-410a-a3ab-76b9c933b935)

监测日志里面，显示成功发送
![image](https://github.com/mouday/domain-admin/assets/5445791/6ed7e021-d81e-42ff-9856-92859988b85b)

**Comment by mouday** [comment]
测试邮件可以正常发送吗？还有一种情况是不满足到期时间小于等于3天，也不会发送，日志记录的应该是检查通知数量

**Comment by mouday** [comment]
对，的触发条件才会通知，你可以把天数设置大一些，比如300天，然后在证书列表点击检查，就会走定时检查一样的逻辑了

**Comment by shiqianwei0508** [comment]
> 对，的触发条件才会通知，你可以把天数设置大一些，比如300天，然后在证书列表点击检查，就会走定时检查一样的逻辑了

ok 感谢解答。
