### ISSUE TITLE
域名日期检测不到

### ISSUE THREAD

**Issue by obaby** [mouday/domain-admin#39]
后缀:ws, cm, by 
上面三个都不行。
麻烦看看~~

**Comment by mouday** [comment]
<img width="426" alt="image" src="https://github.com/mouday/domain-admin/assets/24365682/c76805a3-a51f-45c3-b3b6-5bec6ebc950e">

**Comment by mouday** [comment]
感谢反馈，v1.4.28 已支持

**Comment by obaby** [comment]
多谢
