### ISSUE TITLE
ws后缀貌似还是有问题

### ISSUE THREAD

**Issue by obaby** [mouday/domain-admin#40]
刚试了一下，另外两个确实ok了。但是ws还有点问题，
你试试我的这个h4ck.ws域名。
多谢。

**Comment by obaby** [comment]
额，知道问题在哪里了。域名大小写的问题，如果域名全部大写会失败。
H4CK.WS 无法获取时间，但是h4ck.ws是可以的。

**Comment by obaby** [comment]
.lc 无法获取时间

**Comment by mouday** [comment]
经测试，`.lc` 后缀域名确实无法获取信息，可以手动添加过期时间

**Comment by obaby** [comment]
ok
