### ISSUE TITLE
【需求】子域名自动拉取

### ISSUE THREAD

**Issue by wenyurush** [mouday/domain-admin#41]
当添加一个域名的时候，可以设置一个开关，是否自动拉取子域名及证书信息。

域名可以通过 crt.sh 获取 

示例
https://crt.sh/?q=abc.com

后期，只要添加一个主域名，自动把已经有子域名的ssl证书获取到，然后删除就行了，省的一个一个加

**Comment by mouday** [comment]
新版本 v1.4.32 已支持，感谢提供的建议

**Comment by wenyurush** [comment]
真棒，我去研究研究
