### ISSUE TITLE
1.4.34 更新时间不更新

### ISSUE THREAD

**Issue by obaby** [mouday/domain-admin#43]
![Jietu20230714-091009](https://github.com/mouday/domain-admin/assets/4133066/1eec2cd4-0d1e-4344-ad9b-19d1f659a1ef)
域名天数是对的，但是更新时间不是最新的。

**Comment by mouday** [comment]
域名信息有一个缓存，临期30天才会触发更新，实践发现，如果全都更新会有更新失败的问题，查询接口有请求限制

<img width="986" alt="image" src="https://github.com/mouday/domain-admin/assets/24365682/1c2e1b6a-1a18-4efd-9565-29df82767efb">

**Comment by obaby** [comment]
了解，多谢
