### ISSUE TITLE
为什么有些域名的证书无法识别出来？

### ISSUE THREAD

**Issue by runfali** [mouday/domain-admin#44]
为什么有些域名的证书无法识别出来？
如下面两个：health.sina.cn、www.wenwo.com

**Comment by mouday** [comment]
测试可以获取，我的运行环境是:

- 阿里云ESC
- domain-admin版本号v1.5.1

<img width="1413" alt="image" src="https://github.com/mouday/domain-admin/assets/24365682/1ee3cd18-14c7-420c-93f9-a565e4ecc834">
<img width="1411" alt="image" src="https://github.com/mouday/domain-admin/assets/24365682/98600688-d68b-49e2-8f41-70d03f95d12b">

**Comment by runfali** [comment]
![image](https://github.com/mouday/domain-admin/assets/39327978/5915f286-35a5-4617-8f12-22bd034fd390)
我的是在公司内网K8S集群上，测试获取其他的域名都没问题，版本也是 v1.5.1

**Comment by mouday** [comment]
要确保运行环境能访问到网站才可以，在工具箱试试看能不能查询到信息

<img width="1436" alt="image" src="https://github.com/mouday/domain-admin/assets/24365682/e3bc11fd-7988-40bd-a45d-26762e3cb515">

**Comment by runfali** [comment]
我部署到k8s集群外就好了....

**Comment by mouday** [comment]
之前有也有人遇到过类似问题，说是反向代理配置有问题

<img width="425" alt="image" src="https://github.com/mouday/domain-admin/assets/24365682/94bc1dc7-4b11-4887-98a6-027fad6e731a">
