### ISSUE TITLE
有个网站无法检测到证书状态

### ISSUE THREAD

**Issue by shiqianwei0508** [mouday/domain-admin#45]
域名： www.freedo3d.com

![image](https://github.com/mouday/domain-admin/assets/5445791/35ba3fd7-97f4-408e-8b0f-afb4ea681a51)

![image](https://github.com/mouday/domain-admin/assets/5445791/d4425e1e-6fe0-4b2e-b2b0-5c58027c6623)

![image](https://github.com/mouday/domain-admin/assets/5445791/a0819f2a-a38d-44c7-a91d-3760bd4b6dc6)

网站在一个建站平台上

**Comment by mouday** [comment]
我这里可以检测到的，domain-admin 部署到阿里云ECS上的

<img width="1915" alt="image" src="https://github.com/mouday/domain-admin/assets/24365682/3100c412-248f-456c-9a2b-fd1ccf1432b6">

**Comment by shiqianwei0508** [comment]
> 我这里可以检测到的，domain-admin 部署到阿里云ECS上的
> 
> <img alt="image" width="1915" src="https://user-images.githubusercontent.com/24365682/254435734-3100c412-248f-456c-9a2b-fd1ccf1432b6.png">

![image](https://github.com/mouday/domain-admin/assets/5445791/0a6da2b8-fba6-4576-8fe0-02e33d6b8996)
无论部署在公司内网，还是腾讯云服务器上，都是一样的结果。

**Comment by mouday** [comment]
在工具箱里边试试能不能查到

<img width="1894" alt="image" src="https://github.com/mouday/domain-admin/assets/24365682/7d5aece9-ed62-450f-95fc-9b80fc0f850d">

**Comment by shiqianwei0508** [comment]
> 在工具箱里边试试能不能查到
> 
> <img alt="image" width="1894" src="https://user-images.githubusercontent.com/24365682/255778020-7d5aece9-ed62-450f-95fc-9b80fc0f850d.png">

能

**Comment by mouday** [comment]
说明网络没有问题，应该是其他问题了，其他域名可以正常查询到时间吗

**Comment by shiqianwei0508** [comment]
> 说明网络没有问题，应该是其他问题了，其他域名可以正常查询到时间吗

还有几个，也是查不到，dtsdata.g-bim.cn，installpackages.gbim.vip，terrain.gbim360.com，都是工具箱里面的证书查询可以查到的

**Comment by shiqianwei0508** [comment]
回退到1.4.19版本，域名检测恢复正常，我就不升级了。
