### ISSUE TITLE
关于监控

### ISSUE THREAD

**Issue by zfwV** [mouday/domain-admin#46]
作者您好，关于您这个项目，我使用邮箱或者WEBHOOK的方式去进行告警通知，都没有生效，邮箱已经更换过端口了，还行不行喔，是什么原因呢
![image](https://github.com/mouday/domain-admin/assets/137685062/e403dae2-fcf6-42c9-900f-5a18aa1e4cd7)
![image](https://github.com/mouday/domain-admin/assets/137685062/3d6391d0-fea4-4932-a53e-850c9d695b53)

**Comment by mouday** [comment]
看样子，邮件是验证失败，webhook是接收服务器需要让你登录
