### ISSUE TITLE
异步任务 没有完成时间，不知道如何停止

### ISSUE THREAD

**Issue by dzvision** [mouday/domain-admin#49]
不知道为什么其中一个异步任务没有完成时间，也无法强制停止。（也看不出成功失败，因为我感觉添加成功了）

![screenshot-20230820-215054](https://github.com/mouday/domain-admin/assets/5590839/a7ebc7e7-86ae-407a-a6c6-f31bbed7f462)

**Comment by mouday** [comment]
期间有重启吗，如果有可能回中断，没有结束时间；还可能是耗时确实很长，不过看着是有点异常，正常来说不会那么长时间的

**Comment by dzvision** [comment]
你这么一说，好像有，当时想更新设置的时候弹出错误database is lock. 后来重启过，不知道重启的时候有没有打断当时的进程，理论上应该没有，因为我是过了一段时间搞不了那个错误database is lock才去重启。

**Comment by mouday** [comment]
如果经常出现`database is lock` ,可以换成mysql，文档中有配置参数

**Comment by dzvision** [comment]
就是那一次出现，之后都没出现， 本身就是用mysql的。 这个异步任务时间还在上升，有办法停止吗？

**Comment by mouday** [comment]
清空日志，这个时间是根据开始时间计算的，如果没有结束，就不会固定
