### ISSUE TITLE
功能升级建议和bug

### ISSUE THREAD

**Issue by huguangjun580** [mouday/domain-admin#50]
我使用的版本的web版，实例应用是群晖docker里面的套件安装，是网页方式打开的（所以它应该的个docker的web版），在初次使用过程中遇到了一个bug和一个功能上的升级建议（可作参考）。

功能上升级：
1、在添加域名的时候，最好可以给域名增加一个备用的字段添加保存，目的好备注该域名是什么。
2、针对于第一条建议的基础上，可以进一步升级，对于检测域名的SSL证书日期，可以设置成自动检测或者手动检测（手动检测，就是可以自己手填也行）。
3、关于邮件发送通知上，建议可以设置全部通知的基础上再增加可以单独发送只是即将过期或者已过期的域名SSL证书到期通知。

遇到的功能bug：
1、主设置过期通知是3天。我在添加域名的时候，发现该域名的SSL证书已经到期了，但是检测出来的域名SSL证书是没有过期的（它的时间还剩312天），所以这里的不对的，它应该是个bug，希望进一步改进。

**Comment by mouday** [comment]
以上问题，新版本已经支持了，你用的是什么版本呢？

**Comment by huguangjun580** [comment]
我用的是群晖NAS套件，里面的源码地址指向这里。在安装的时候它是个docker版。套件源是云梦(缔梦天城)，那就应该云梦的套件没有更新吧

**Comment by mouday** [comment]
目前最新版是 v1.5.16 ，web界面左下角有版本号显示

**Comment by huguangjun580** [comment]
是我这边套件里面的版本低了，目前我看了下是1.0.4，提示目前新版本是V1.5.16。我进云梦套件群反馈下吧

**Comment by mouday** [comment]
是的，需要升级了

**Comment by mouday** [comment]
![image](https://github.com/mouday/domain-admin/assets/24365682/f4b152a0-fd42-47be-a16a-99c5fd60ba3e)
