### ISSUE TITLE
国外注册的域名好像获取不到域名信息

### ISSUE THREAD

**Issue by longxwl** [mouday/domain-admin#54]
如题

**Comment by mouday** [comment]
部分域名确实不行，可以把后缀给我，我查一下问题

**Comment by longxwl** [comment]
.kr 
.my

**Comment by mouday** [comment]
.kr已支持，.my查询不到信息，可以手动设置 已发布 v1.5.21

**Comment by mouday** [comment]
<img width="798" alt="image" src="https://github.com/mouday/domain-admin/assets/24365682/c2f076b8-e867-4eca-896b-ee2cdc033337">

**Comment by longxwl** [comment]
好的 感谢
