### ISSUE TITLE
SMTP服务需要增加SMTP验证用户名问题

### ISSUE THREAD

**Issue by poctopus** [mouday/domain-admin#55]
当我使用Resend.com服务的时候，SMTP验证的用户名是固定值resend，密码按照要求生成是token，按照现在程序配置的逻辑，没有发件人这一项可以填写，建议添加上发送人邮箱。

**Comment by mouday** [comment]
可以使用webhook对接Resend.com，Resend提供了api接口

<img width="773" alt="image" src="https://github.com/mouday/domain-admin/assets/24365682/6fcc7f54-3a7b-4024-8e9c-e7d065b89554">

**Comment by poctopus** [comment]
牛皮了，这个简单了。
