### ISSUE TITLE
[建议]可以加上服务器端口监控

### ISSUE THREAD

**Issue by Enoydu** [mouday/domain-admin#58]
这个界面简洁舒服，该有的功能都有了。希望大佬可以加上服务器端口监控，或者新开一个仓库？我看到证书监控已经可以检测端口，可能稍微改一下设置，端口不通就发通知，就是一个监控各种服务的功能了？也可以加上ping和IP检测。
![11](https://github.com/mouday/domain-admin/assets/68388226/4af3c965-5bd2-48fd-bcd9-edcc72fdb2bd)

另外域名后缀.ch检测不了，可能是whois限制。
![2](https://github.com/mouday/domain-admin/assets/68388226/fc587195-7607-4fc6-b3f3-4d74ec15ed45)

**Comment by mouday** [comment]
ch后缀确实查不到信息

端口监控需要实时性比较高，之前有人也提过类似需求，之后可能会增加该功能

**Comment by mouday** [comment]
v1.6.2版本已增加http检测
