### ISSUE TITLE
com.au的国外域名无法查询到域名的信息

### ISSUE THREAD

**Issue by akinoneko** [mouday/domain-admin#59]
<img width="1297" alt="image" src="https://github.com/mouday/domain-admin/assets/6488645/43b52171-507e-410f-85db-7d384ef93c6d">
如图 只支持顶级域名么

**Comment by mouday** [comment]
.au 的信息确实查询不到，没有有效期时间信息，如果需要监控，只能手动填写了

![image](https://github.com/mouday/domain-admin/assets/24365682/d45193c2-2660-4a95-9f77-764459767ca1)

**Comment by akinoneko** [comment]
好的谢谢
