### ISSUE TITLE
请问数据存放的目录在哪里

### ISSUE THREAD

**Issue by star7th** [mouday/domain-admin#6]
因为是docker安装，所以每次重启都会被还原。我需要把数据目录持久化挂载出来，才能避免每次被还原

**Comment by mouday** [comment]
启动的时候试试 `-v` 参数，同步本地文件

**Comment by star7th** [comment]
我最终的解决方法是把代码整份映射到容器内部的/app目录。

**Comment by ixinshang** [comment]
我也遇到持久化的问题了，还在看怎么弄。
@mouday  能否告知一下挂载的目录呢

**Comment by mouday** [comment]
> 我也遇到持久化的问题了，还在看怎么弄。 @mouday 能否告知一下挂载的目录呢

```bash
docker run \
-v $(pwd)/database:/app/database \
-v $(pwd)/logs:/app/logs \
-p 8000:8000 \
mouday/domain-admin:0.0.18
```

**Comment by ixinshang** [comment]
> > 我也遇到持久化的问题了，还在看怎么弄。 @mouday 能否告知一下挂载的目录呢
> 
> ```shell
> docker run \
> -v $(pwd)/database:/app/database \
> -v $(pwd)/logs:/app/logs \
> -p 8000:8000 \
> mouday/domain-admin:0.0.18
> ```

好的，谢谢
