### ISSUE TITLE
[Bug] Edge浏览器兼容问题

### ISSUE THREAD

**Issue by Physton** [mouday/domain-admin#61]
感谢开发出这么好的工具，辛苦了。麻烦看下以下浏览器兼容问题。

Chrome 浏览器：正常显示
![Snipaste_2023-09-27_00-00-40](https://github.com/mouday/domain-admin/assets/12066768/dc1a0932-1d44-4fa9-ab31-dcb76bbf6344)

Edge 浏览器：顶部导航栏，所有的子菜单都无法显示。最严重的是个人头像里的子菜单，导致无法看到修改密码的按钮。
![Snipaste_2023-09-27_00-00-49](https://github.com/mouday/domain-admin/assets/12066768/c0c8cb8d-a682-44b7-9262-5d5cee5bb0a7)

Chrome 浏览器：可以正常显示和输入
![Snipaste_2023-09-27_00-01-10](https://github.com/mouday/domain-admin/assets/12066768/624d9905-c394-4fe2-842c-947aefaf5123)

Edge 浏览器：无法显示默认内容和输入
![Snipaste_2023-09-27_00-01-22](https://github.com/mouday/domain-admin/assets/12066768/7ae1ec7d-5411-4992-9168-67536196eed9)

这两个是比较严重的问题，影响正常使用。
另外还有很多显示错位、图标不显示等问题，但不影响使用。

Mac、Windows系统均有问题，Edge都是最新版。

希望开发者能够修改。

**Comment by Physton** [comment]
补充一下：我是采用docker部署的

**Comment by mouday** [comment]
我的mac版本太低，Edge不支持了，可以考虑帮忙PR吗

**Comment by Physton** [comment]
已经找到原因，是油猴其中一个脚本的问题，禁用掉就好了。
[网页通用验证码](https://greasyfork.org/zh-CN/scripts/440083-%E7%BD%91%E9%A1%B5%E9%80%9A%E7%94%A8%E9%AA%8C%E8%AF%81%E7%A0%81)

**Comment by mouday** [comment]
好的👌
