### ISSUE TITLE
docker启动的还是报错

### ISSUE THREAD

**Issue by jindc123** [mouday/domain-admin#62]
![image](https://github.com/mouday/domain-admin/assets/43500245/d9536bfe-54fc-47a0-9a57-e90fdd6c2563)

**Comment by mouday** [comment]
试试不用latest版本，指定一个具体的版本试试

**Comment by jindc123** [comment]
> 试试不用latest版本，指定一个具体的版本试试

我不知道都有哪些版本，，，你可以给一个么？ 
还有你们微信群二维码已经过期了，想进群

**Comment by mouday** [comment]
目前最新版是：v1.5.24

**Comment by mouday** [comment]
微信群二维码已更新

**Comment by jindc123** [comment]
那我试一下 v1.5.20

**Comment by jindc123** [comment]
![image](https://github.com/mouday/domain-admin/assets/43500245/7ccb6014-38d2-44cb-8175-1bbdeb52ac24)
这个版本也是有报错的

**Comment by mouday** [comment]
这个报错可以忽略，可以访问到吗？

**Comment by jindc123** [comment]
![image](https://github.com/mouday/domain-admin/assets/43500245/b4233868-81fa-49db-9416-0ea7ad461cce)
可以访问到了，但是添加域名时 又有新的报错了

**Comment by mouday** [comment]
试试v1.5.24 或者移除你的database logs文件夹重新启动

**Comment by jindc123** [comment]
> 试试v1.5.24 或者移除你的database logs文件夹重新启动

1.5.24是可以的，感谢 感谢！
