### ISSUE TITLE
企业微信机器人webhook

### ISSUE THREAD

**Issue by wintsa123** [mouday/domain-admin#65]
测试，这是正常的吗
```json

{
  "msgtype": "text",
  "text": {  
  "content": "你好，{% for row in list %}{{row.domain}} {{row.start_date or '-' }} - {{row.expire_date or '-' }} ({{row.expire_days}}){% endfor %}"
   }
}
```

![image](https://github.com/mouday/domain-admin/assets/47288630/a3e9232f-3a0c-4fbe-bdc0-99dc55b11043)

还有就是能不能针对所有域名和ssl，等快过期自动每天发起webhook，而不是手动设置定时的webhook发起时间。

**Comment by wintsa123** [comment]
{% for row in list %}{{row.domain}} {{row.start_date or '-' }} - {{row.expire_date or '-' }} ({{row.expire_days}}){% endfor %}
我尝试使用这个模板，但读取不出数据

**Comment by mouday** [comment]
增加到期天数试试
