### ISSUE TITLE
更新检测结果不一致

### ISSUE THREAD

**Issue by lesrose** [mouday/domain-admin#67]
起初剩余天数是零天，手动更新后显示正常，
![lQLPJyFNc3eRZ6DNAgrNA-awWlGpkxC0QmcFMTZcB4ClAA_998_522](https://github.com/mouday/domain-admin/assets/48045297/3764b945-42e8-46e4-924b-e59c82148993)

然后执行了全部更新，剩余天数又变成了零天
![42F29A12-2691-40f2-9417-4CA793858587](https://github.com/mouday/domain-admin/assets/48045297/8734058b-2362-4335-ad2a-2519f38db738)

**Comment by mouday** [comment]
是不是服务器不稳定，访问出现故障

**Comment by lesrose** [comment]
有两百个域名，应该是请求频率太高，被拦截了

**Comment by mouday** [comment]
那这个锅我不背[笑]

**Comment by lesrose** [comment]
我加了一个暂停，sleep 7s 就没啥问题了
![image](https://github.com/mouday/domain-admin/assets/48045297/f7b5533c-294a-43c9-9421-c59a76fba850)

**Comment by mouday** [comment]
那检测速度肯定很慢了

**Comment by lesrose** [comment]
差不多半小时
