### ISSUE TITLE
希望能添加一个直接监控SSL证书文件的功能

### ISSUE THREAD

**Issue by hanziqing0630** [mouday/domain-admin#69]
我们是负责安全的部门，有很多证书文件（配置waf、负载时使用），不清楚使用了哪些二级域名，无法直接配置监控，还要去询问主机名、查询端口，希望能够直接上传、监控SSL证书文件。

**Comment by mouday** [comment]
解析证书文件并监控的功能吧？

**Comment by hanziqing0630** [comment]
对的

**Comment by mouday** [comment]
可以试试证书托管功能，不过暂时没有做自动告警，仅做了证书托管列表，后续再增加具体功能

**Comment by 1447262390** [comment]
确实需要这个功能，有时候域名会修改，这样就会漏掉这个证书的监控，能够直接上传证书并且对证书监控确实是非常好的功能

**Comment by mouday** [comment]
可以的，我怎么一个触发事件
