### ISSUE TITLE
.TOP 的域名好像获取不到域名信息

### ISSUE THREAD

**Issue by wenyang0** [mouday/domain-admin#75]
.TOP 的域名好像获取不到域名信息，这个可以支持吗

**Comment by mouday** [comment]
<img width="401" alt="image" src="https://github.com/mouday/domain-admin/assets/24365682/c1a9779b-9e00-4d85-86a2-07f58ab08d44">

支持的，你再试试看

**Comment by wenyang0** [comment]
![image](https://github.com/mouday/domain-admin/assets/86756816/bcb98256-cb20-4869-b5e5-c98b899357b1)
我好多这个域名 都是 获取不到域名的过期天数，是不是哪里需要特殊设置

**Comment by immoke** [comment]
@mouday 作者你好，top域名似乎是有查询限制，我添加了几千个域名，然后只能查询出来14条，其他的就一直无法显示。手动查询提示：Your access is too fast,please try again later.但是平台也没有降低频率的设置的地方
