### ISSUE TITLE
.name域名无法正确获取信息

### ISSUE THREAD

**Issue by lamefox** [mouday/domain-admin#83]
![图片](https://github.com/mouday/domain-admin/assets/4133729/fa878551-1bec-49f3-a157-7c0ec79927f5)
如图所示，.name域名无法正确获取信息

**Comment by mouday** [comment]
是的，这个类型的域名不知道，可以在工具箱里查询原始信息测试
<img width="1142" alt="image" src="https://github.com/mouday/domain-admin/assets/24365682/fe5f2051-86ca-45a2-a534-5aa398b19e09">
