### ISSUE TITLE
.by域名无法获取信息

### ISSUE THREAD

**Issue by obaby** [mouday/domain-admin#84]
.by域名无法获取信息

**Comment by mouday** [comment]
可以获取的，你用的什么版本

我用的域名：filter.by

<img width="740" alt="image" src="https://github.com/mouday/domain-admin/assets/24365682/c3028d88-640f-4f5b-8c95-56deaf42425f">

**Comment by obaby** [comment]
已经更新到最新版，依然不行
![Jietu20240202-163624](https://github.com/mouday/domain-admin/assets/4133066/01319f2c-2a84-4b88-93aa-a5cae92ab850)
![Jietu20240202-163650](https://github.com/mouday/domain-admin/assets/4133066/1217ce1b-ebe4-4d7c-b93d-8d09632cf91a)

**Comment by mouday** [comment]
我看你的截图，不是有域名信息了吗

**Comment by obaby** [comment]
看过期时间，这个是错的。

**Comment by obaby** [comment]
差一年

**Comment by obaby** [comment]
已经续费半个月了

**Comment by mouday** [comment]
这个好像只能手动填写了，不然域名信息更新后又给你刷掉了

**Comment by obaby** [comment]
确认了，貌似是注册局问题
