### ISSUE TITLE
.pro 的域名好像获取不到域名解析信息

### ISSUE THREAD

**Issue by trojan20161207** [mouday/domain-admin#95]
![image](https://github.com/mouday/domain-admin/assets/24422386/c32fcbcd-427c-469b-91a7-2a7c125f5de3)
您好，.pro 的域名好像获取不到域名解析信息，这个可以支持吗
版本是1.6.7

**Comment by mouday** [comment]
我更新一下

**Comment by mouday** [comment]
v1.6.21版本已发布

<img width="780" alt="image" src="https://github.com/mouday/domain-admin/assets/24365682/c5f3c65e-c62b-4456-bff7-1e54dff96195">
